/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdc_assignment2;

/**
 *
 * @author PC
 */
public class MainGUI extends javax.swing.JFrame {
    Player player;
    
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    public void loadMenuButtons(){
        robButton.setVisible(true);
        pyramidButton.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        robButton = new javax.swing.JButton();
        pyramidButton = new javax.swing.JButton();
        saveExitButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        userCreatePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        usernameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(599, 401));
        setSize(new java.awt.Dimension(600, 401));

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        menuButton.setText("Menu");
        menuButton.setVisible(false);
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        robButton.setText("Red or Black");
        robButton.setVisible(false);
        robButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robButtonActionPerformed(evt);
            }
        });

        pyramidButton.setText("Pyramid");
        pyramidButton.setVisible(false);
        pyramidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyramidButtonActionPerformed(evt);
            }
        });

        saveExitButton.setText("Save & Exit");
        saveExitButton.setVisible(false);
        saveExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuButton)
                .addGap(113, 113, 113)
                .addComponent(robButton)
                .addGap(29, 29, 29)
                .addComponent(pyramidButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(saveExitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(menuButton)
                    .addComponent(robButton)
                    .addComponent(pyramidButton)
                    .addComponent(saveExitButton))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Enter Username");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        usernameError.setForeground(new java.awt.Color(255, 0, 0));
        usernameError.setText("Please enter a name! Do not leave blank.");
        usernameError.setVisible(false);

        javax.swing.GroupLayout userCreatePanelLayout = new javax.swing.GroupLayout(userCreatePanel);
        userCreatePanel.setLayout(userCreatePanelLayout);
        userCreatePanelLayout.setHorizontalGroup(
            userCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCreatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(userCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameError)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        userCreatePanelLayout.setVerticalGroup(
            userCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCreatePanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(userCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(usernameError)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        mainPanel.add(userCreatePanel, "card2");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if (jTextField1.getText().trim().equals(""))
        {
            usernameError.setVisible(true);
        }
        else
        {
            player = new Player(jTextField1.getText());
            mainPanel.removeAll();
            mainPanel.add(new MenuPanel(player));
            mainPanel.repaint();
            mainPanel.revalidate();
            confirmButton.setVisible(false);
            saveExitButton.setVisible(true);
            loadMenuButtons();
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void robButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(new RedOrBlackView(player));
        mainPanel.repaint();
        mainPanel.revalidate();
        confirmButton.setVisible(false);
        robButton.setVisible(false);
        pyramidButton.setVisible(false);
        menuButton.setVisible(true);
    }//GEN-LAST:event_robButtonActionPerformed

    private void pyramidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyramidButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(new PyramidView(player));
        mainPanel.repaint();
        mainPanel.revalidate();
        confirmButton.setVisible(false);
        robButton.setVisible(false);
        pyramidButton.setVisible(false);
        menuButton.setVisible(true);
    }//GEN-LAST:event_pyramidButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(new MenuPanel(player));
        mainPanel.repaint();
        mainPanel.revalidate();
        menuButton.setVisible(false);
        loadMenuButtons();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void saveExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveExitButtonActionPerformed
        player.endSession();
        System.exit(0);
    }//GEN-LAST:event_saveExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton pyramidButton;
    private javax.swing.JButton robButton;
    private javax.swing.JButton saveExitButton;
    private javax.swing.JPanel userCreatePanel;
    private javax.swing.JLabel usernameError;
    // End of variables declaration//GEN-END:variables
}
